sudo: required

services:
  - docker

before_install:
  - travis_wait 30 docker build -t degauss/cchmc_batch_geocoder .

script:
  - docker run --rm=TRUE -v "$PWD":/tmp degauss/acs_income my_address_file.csv
  - test -e my_address_file_geocoded.csv || exit 1
